from selenium.webdriver.common.by import By


class OzonCheesesLocators:
    CREAM_CHEESE = (By.XPATH, "//span[contains(text(), 'Сыр Сливочный Ozon fresh, 50%, 200 г')]")
    CREAM_CHEESE_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр Сливочный Ozon fresh, 50%, 200 г')]")
    DUTCH_CHEESE = (By.XPATH, "//span[contains(text(), 'Сыр Голландский Ozon fresh, 45%, нарезка, 125 г')]")
    DUTCH_CHEESE_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр Голландский Ozon fresh, 45%, нарезка, 125 г')]")
    CHEESE_WITH_HERBS = (By.XPATH, "//span[contains(text(), 'Сыр с пряными травами Ozon fresh, 50%,  200 г')]")
    CHEESE_WITH_HERBS_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр с пряными травами Ozon fresh, 50%,  200 г')]")
    CHEESE_WITH_TOMATO_BASIL = (
        By.XPATH, "//span[contains(text(), 'Сыр с томатом и базиликом Ozon fresh, 50%, нарезка, 125 г')]")
    CHEESE_WITH_TOMATO_BASIL_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр с томатом и базиликом Ozon fresh, 50%, нарезка, 125 г')]")
    TIILSITER_CHEESE = (By.XPATH, "//span[contains(text(), 'Сыр Тильзитер Ozon fresh, 45%, 200 г')]")
    TIILSITER_CHEESE_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр Тильзитер Ozon fresh, 45%, 200 г')]")
    HARD_CHEESE_PALERMO = (By.XPATH, "//span[contains(text(), 'Сыр твердый Palermo Ozon fresh, 40%, 180 г')]")
    HARD_CHEESE_PALERMO_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр твердый Palermo Ozon fresh, 40%, 180 г')]")
    CHEES_FETA = (By.XPATH, "//span[contains(text(), 'Сыр Фета Ozon fresh, 45%, рассольный, 200 г')]")
    CHEES_FETA_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр Фета Ozon fresh, 45%, рассольный, 200 г')]")
    BURRATA_CHEESE = (By.XPATH, "//span[contains(text(), 'Сыр Буррата Ozon fresh, 50%, 125 г')]")
    BURRATA_CHEESE_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр Буррата Ozon fresh, 50%, 125 г')]")
    CHEESE_MOZZARELLA_MINI = (By.XPATH, "//span[contains(text(), 'Сыр Моцарелла Мини Ozon fresh, 50%, 100 г')]")
    CHEESE_MOZZARELLA_MINI_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр Моцарелла Мини Ozon fresh, 50%, 100 г')]")
    HARD_CHEESE_PALERMO_SOLID = (By.XPATH, "//span[contains(text(), 'Сыр твердый Palermo Ozon fresh, 40%, 180 г')]")
    HARD_CHEESE_PALERMO_SOLID_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр твердый Palermo Ozon fresh, 40%, 180 г')]")
    PICKLED_CHESEE_BRYNZA = (By.XPATH, "//span[contains(text(), 'Сыр рассольный Брынза Ozon fresh, 30%, 250г')]")
    PICKLED_CHESEE_BRYNZA_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр рассольный Брынза Ozon fresh, 30%, 250г')]")
    CHEESE_RUSSIAN = (By.XPATH, "//span[contains(text(), 'Сыр Российский Ozon fresh, 45%, 200 г')]")
    CHEESE_RUSSIAN_VALUE = (By.XPATH, "//h1[contains(text(), 'Сыр Российский Ozon fresh, 45%, 200 г')]")
    PRICE = (By.XPATH, "//div[@slot='content']//span[contains(text(), '₽')]")
